version: "3"

networks:
  app-etcd-cluster_net-torcs:
    external: true

services:
  client:
    build: .
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    ports:
      - "8001:8001"
    networks:
      - app-etcd-cluster_net-torcs
