version: "3"

networks:
  net-torcs:
    driver: bridge
    ipam:
      config:
        - subnet: "172.20.0.0/16"
services:
  Etcd:
    image: 'my-etcd:latest'
    build: ./etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - 2379:2379
      - 2380:2380
    networks:
      - net-torcs
      
  app:
    image: my-app:latest
    build: ./app
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
      - LD_LIBRARY_PATH=/usr/local/lib:/libetcd-cpp-api.so
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    ports:
      - "8000:8000"
    networks:
      net-torcs:
        ipv4_address: 172.20.0.3
    depends_on:
      - "Etcd"
