version: "3"

networks:
  net-torcs:
    driver: bridge

services:
  app:
    image: my-app:latest
    build: .
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    ports:
      - "8000:8000"
    networks:
      - net-torcs

