version: "3"

networks:
  torcs-docker-137_net-torcs:
    external: true

services:
  client:
    image: my-client:latest
    build: .
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    ports:
      - "8001:8001"
    networks:
      - torcs-docker-137_net-torcs
