FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive
ARG DISPLAY=$DISPLAY

RUN apt-get update && apt-get install -y \
    g++ \
    libglib2.0-dev \
    libgl1-mesa-dev \
    libglu1-mesa-dev \
    freeglut3-dev \
    libplib-dev \
    libopenal-dev \
    libalut-dev \
    libxi-dev \
    libxmu-dev \
    libxrender-dev \
    libxrandr-dev \
    libpng-dev \
    libvorbis-dev \
    libxxf86vm-dev \
    wget \
    unzip \
    sudo \
    xorg openbox \
    xterm \
    cmake \
    make

RUN apt-get install -y alsa-utils

RUN apt-get install -y libopencv-dev python3-opencv

RUN apt-get install -y libcpprest-dev

RUN apt-get install -y libboost-all-dev libssl-dev

RUN apt-get install -y libgrpc-dev \
        libgrpc++-dev \
        libprotobuf-dev \
        protobuf-compiler-grpc

WORKDIR /tmp

RUN wget -O etcd-cpp-apiv3.zip https://github.com/etcd-cpp-apiv3/etcd-cpp-apiv3/archive/master.zip

RUN unzip etcd-cpp-apiv3.zip

WORKDIR /tmp/etcd-cpp-apiv3-master

RUN mkdir build

WORKDIR /tmp/etcd-cpp-apiv3-master/build

RUN cmake ..

RUN make -j$(nproc) && make install

WORKDIR /tmp

RUN wget -O TORCS_multi_docker.zip https://github.com/DrSgre/TORCS_multi_docker/archive/master.zip

RUN unzip TORCS_multi_docker.zip

WORKDIR /tmp/TORCS_multi_docker-master/torcs-1.3.7-patched

RUN export CFLAGS="-fPIC" && export CPPFLAGS=$CFLAGS && export CXXFLAGS=$CFLAGS

RUN ./configure --prefix=$(pwd)/BUILD

RUN make clean && make && make install && make datainstall

RUN ["chmod", "755", "./BUILD/bin/torcs"]

ARG LD_LIBRARY_PATH=/usr/local/lib/libetcd-cpp-api.so

WORKDIR /tmp/TORCS_multi_docker-master/torcs-1.3.7-patched/screenpipe

CMD ../BUILD/bin/torcs

## DISCARDED DISPLAY MANAGEMENT

#ENV DISPLAY=':0.0'
#RUN sed -i 's/ForwardX11 no/ForwardX11 yes/' /etc/ssh/ssh_config
#RUN cat /etc/ssh/ssh_config
#RUN touch ~/.Xauthority
#RUN xauth generate $DISPLAY . trusted 
#RUN xauth add ${HOST}:0 . $(xxd -l 16 -p /dev/urandom)
#RUN xauth list
#RUN xhost +local:docker 
#RUN xterm
#CMD sudo ./torcs -r ~/.torcs/config/raceman/champ.xml
#CMD sudo ./torcs
#ENTRYPOINT ["tail", "-f", "/dev/null"]

## DISCARDED SSH MANAGEMENT

#RUN touch /tmp/myfolder
#RUN apt-get update && apt-get install -y openssh-server
#RUN mkdir /var/run/sshd
#RUN echo 'root:mypassword' | chpasswd
#RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
#RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd
#EXPOSE 22
#RUN echo 'root:Drsgre.1' | chpasswd
#RUN mkdir -p /home/app/.ssh
#RUN echo "DISPLAY=$DISPLAY" >> /home/app/.ssh/environment
#WORKDIR /
#CMD ["/usr/sbin/sshd", "-D"]
